/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bosszhipin.thrift;

import org.apache.thrift.TException;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import javax.annotation.Generated;
import java.util.*;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-04-26")
public class HField implements org.apache.thrift.TBase<HField, HField._Fields>, java.io.Serializable, Cloneable, Comparable<HField> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HField");

  private static final org.apache.thrift.protocol.TField VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("value", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField HIGHLIGHTS_FIELD_DESC = new org.apache.thrift.protocol.TField("highlights", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new HFieldStandardSchemeFactory());
    schemes.put(TupleScheme.class, new HFieldTupleSchemeFactory());
  }

  public String value; // required
  public List<HighLightOffset> highlights; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VALUE((short)1, "value"),
    HIGHLIGHTS((short)2, "highlights");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VALUE
          return VALUE;
        case 2: // HIGHLIGHTS
          return HIGHLIGHTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.HIGHLIGHTS};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VALUE, new org.apache.thrift.meta_data.FieldMetaData("value", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HIGHLIGHTS, new org.apache.thrift.meta_data.FieldMetaData("highlights", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, HighLightOffset.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HField.class, metaDataMap);
  }

  public HField() {
  }

  public HField(
    String value)
  {
    this();
    this.value = value;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HField(HField other) {
    if (other.isSetValue()) {
      this.value = other.value;
    }
    if (other.isSetHighlights()) {
      List<HighLightOffset> __this__highlights = new ArrayList<HighLightOffset>(other.highlights.size());
      for (HighLightOffset other_element : other.highlights) {
        __this__highlights.add(new HighLightOffset(other_element));
      }
      this.highlights = __this__highlights;
    }
  }

  public HField deepCopy() {
    return new HField(this);
  }

  @Override
  public void clear() {
    this.value = null;
    this.highlights = null;
  }

  public String getValue() {
    return this.value;
  }

  public HField setValue(String value) {
    this.value = value;
    return this;
  }

  public void unsetValue() {
    this.value = null;
  }

  /** Returns true if field value is set (has been assigned a value) and false otherwise */
  public boolean isSetValue() {
    return this.value != null;
  }

  public void setValueIsSet(boolean value) {
    if (!value) {
      this.value = null;
    }
  }

  public int getHighlightsSize() {
    return (this.highlights == null) ? 0 : this.highlights.size();
  }

  public java.util.Iterator<HighLightOffset> getHighlightsIterator() {
    return (this.highlights == null) ? null : this.highlights.iterator();
  }

  public void addToHighlights(HighLightOffset elem) {
    if (this.highlights == null) {
      this.highlights = new ArrayList<HighLightOffset>();
    }
    this.highlights.add(elem);
  }

  public List<HighLightOffset> getHighlights() {
    return this.highlights;
  }

  public HField setHighlights(List<HighLightOffset> highlights) {
    this.highlights = highlights;
    return this;
  }

  public void unsetHighlights() {
    this.highlights = null;
  }

  /** Returns true if field highlights is set (has been assigned a value) and false otherwise */
  public boolean isSetHighlights() {
    return this.highlights != null;
  }

  public void setHighlightsIsSet(boolean value) {
    if (!value) {
      this.highlights = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case VALUE:
      if (value == null) {
        unsetValue();
      } else {
        setValue((String)value);
      }
      break;

    case HIGHLIGHTS:
      if (value == null) {
        unsetHighlights();
      } else {
        setHighlights((List<HighLightOffset>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case VALUE:
      return getValue();

    case HIGHLIGHTS:
      return getHighlights();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case VALUE:
      return isSetValue();
    case HIGHLIGHTS:
      return isSetHighlights();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof HField)
      return this.equals((HField)that);
    return false;
  }

  public boolean equals(HField that) {
    if (that == null)
      return false;

    boolean this_present_value = true && this.isSetValue();
    boolean that_present_value = true && that.isSetValue();
    if (this_present_value || that_present_value) {
      if (!(this_present_value && that_present_value))
        return false;
      if (!this.value.equals(that.value))
        return false;
    }

    boolean this_present_highlights = true && this.isSetHighlights();
    boolean that_present_highlights = true && that.isSetHighlights();
    if (this_present_highlights || that_present_highlights) {
      if (!(this_present_highlights && that_present_highlights))
        return false;
      if (!this.highlights.equals(that.highlights))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_value = true && (isSetValue());
    list.add(present_value);
    if (present_value)
      list.add(value);

    boolean present_highlights = true && (isSetHighlights());
    list.add(present_highlights);
    if (present_highlights)
      list.add(highlights);

    return list.hashCode();
  }

  @Override
  public int compareTo(HField other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetValue()).compareTo(other.isSetValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.value, other.value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHighlights()).compareTo(other.isSetHighlights());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHighlights()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.highlights, other.highlights);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("HField(");
    boolean first = true;

    sb.append("value:");
    if (this.value == null) {
      sb.append("null");
    } else {
      sb.append(this.value);
    }
    first = false;
    if (isSetHighlights()) {
      if (!first) sb.append(", ");
      sb.append("highlights:");
      if (this.highlights == null) {
        sb.append("null");
      } else {
        sb.append(this.highlights);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    if (value == null) {
      throw new TProtocolException("Required field 'value' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class HFieldStandardSchemeFactory implements SchemeFactory {
    public HFieldStandardScheme getScheme() {
      return new HFieldStandardScheme();
    }
  }

  private static class HFieldStandardScheme extends StandardScheme<HField> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, HField struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.value = iprot.readString();
              struct.setValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // HIGHLIGHTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.highlights = new ArrayList<HighLightOffset>(_list0.size);
                HighLightOffset _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new HighLightOffset();
                  _elem1.read(iprot);
                  struct.highlights.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setHighlightsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, HField struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.value != null) {
        oprot.writeFieldBegin(VALUE_FIELD_DESC);
        oprot.writeString(struct.value);
        oprot.writeFieldEnd();
      }
      if (struct.highlights != null) {
        if (struct.isSetHighlights()) {
          oprot.writeFieldBegin(HIGHLIGHTS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.highlights.size()));
            for (HighLightOffset _iter3 : struct.highlights)
            {
              _iter3.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class HFieldTupleSchemeFactory implements SchemeFactory {
    public HFieldTupleScheme getScheme() {
      return new HFieldTupleScheme();
    }
  }

  private static class HFieldTupleScheme extends TupleScheme<HField> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, HField struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.value);
      BitSet optionals = new BitSet();
      if (struct.isSetHighlights()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetHighlights()) {
        {
          oprot.writeI32(struct.highlights.size());
          for (HighLightOffset _iter4 : struct.highlights)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, HField struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.value = iprot.readString();
      struct.setValueIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.highlights = new ArrayList<HighLightOffset>(_list5.size);
          HighLightOffset _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new HighLightOffset();
            _elem6.read(iprot);
            struct.highlights.add(_elem6);
          }
        }
        struct.setHighlightsIsSet(true);
      }
    }
  }

}

